In [1]:
#import all necessary libraris
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error,mean_absolute_error
import warnings as wr 
wr.filterwarnings('ignore')

In [2]:
#import dataset
data = pd.read_csv("weight-height.csv")
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
data.describe()

Height       Weight
count  8555.000000  8555.000000
mean     66.809925   165.632735
std       3.851454    32.043922
min      54.616858    65.780000
25%      63.957684   139.876803
50%      66.985923   168.521567
75%      69.604427   190.666305
max      80.450000   269.989698

In [4]:
#check null value is there any null value there 
data.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [5]:
#check unique labels  total values
data["Gender"].value_counts()

Male      5000
Female    3555
Name: Gender, dtype: int64

#  Perform Label Encoding

### here i use label encoding , in dataset in gender column not numeric labels for this reason use encoding 

In [6]:
le = LabelEncoder()
data.Gender =le.fit_transform(data[["Gender"]])

In [7]:
x= data.drop("Weight",axis=1)
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [8]:
y = data[["Weight"]]

y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

# Train Test Split Data

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = .30, random_state = 1) #train_size = .70 

In [10]:
#check all shape here 
print('Shape of X_train = ', x_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', x_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5988, 2)
Shape of y_train =  (5988, 1)
Shape of X_test =  (2567, 2)
Shape of y_test =  (2567, 1)


In [11]:
x_train.head()

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [12]:
y_train.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

# Perform Linear Regression 

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
l_reg = LinearRegression()
l_reg

LinearRegression()

In [15]:
l_reg.fit(x_train,y_train)

LinearRegression()

In [16]:
l_reg.coef_

array([[19.34359322,  5.96887438]])

In [17]:
l_reg.intercept_

array([-244.55280903])

In [18]:
predcition = l_reg.predict(x_test)

In [19]:
predcition

array([[143.83013436],
       [197.53417989],
       [184.63515112],
       ...,
       [160.7078525 ],
       [186.82852694],
       [201.4226542 ]])

In [20]:
l_reg.predict([[1,71.476101]])

array([[201.42265253]])

In [21]:
lr_score=l_reg.score(x_train,y_train)
lr_score

0.8972135459668118

In [22]:
lr_score=l_reg.score(x_test,y_test)
lr_score

0.905995960709116

In [23]:
mean_squared_error(y_test,predcition)

99.67250998070031

In [24]:
mean_absolute_error(y_test, predcition)

7.98213259272913

# KNN   Regressor weights="uniform"

In [25]:
from sklearn.neighbors import KNeighborsRegressor

In [26]:
K_nei_reg_uniform = KNeighborsRegressor(weights= 'uniform',n_neighbors=99)
K_nei_reg_uniform

KNeighborsRegressor(n_neighbors=99)

In [27]:
K_nei_reg_uniform.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=99)

In [28]:
predcition2 = K_nei_reg_uniform.predict(x_test)

In [29]:
mean_squared_error(y_test,predcition2)

104.00830234751145

In [30]:
mean_absolute_error(y_test,predcition2)

8.122394753568406

In [31]:
kr_uni_score = K_nei_reg_uniform.score(x_test,y_test)
kr_uni_score

0.9019067489887957

In [32]:
x_test.iloc[-1, :]

Gender     1.000000
Height    71.476101
Name: 233, dtype: float64

In [33]:
y_test.iloc[-1]

Weight    195.392618
Name: 233, dtype: float64

In [34]:
y_test.shape

(2567, 1)

In [35]:
K_nei_reg_uniform.predict([x_test.iloc[-1, :]])

array([[201.15780976]])

# KNN   Regressor  weights='distance' 

In [36]:
K_neigh_distance = KNeighborsRegressor(weights= 'distance',n_neighbors=99)

In [37]:
K_neigh_distance.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=99, weights='distance')

In [38]:
predcition3 = K_neigh_distance.predict(x_test)

In [39]:
mean_squared_error(y_test,predcition3)

119.82783287285932

In [40]:
mean_absolute_error(y_test,predcition3)

8.66953183460295

In [41]:
kr_dis_score = K_neigh_distance.score(x_test,y_test)
kr_dis_score

0.8869868902498507

In [42]:
predcition3

array([[147.34891636],
       [197.70696685],
       [182.72646495],
       ...,
       [159.10722409],
       [184.29815187],
       [201.40094163]])

In [43]:
y_test.shape

(2567, 1)

In [44]:
x_test.shape

(2567, 2)

# KNN Classifier:

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [46]:
data.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [47]:
x=data.drop('Gender',axis=1)

In [48]:
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [49]:
y = data[['Gender']]
y.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [50]:
x_train1,x_test1,y_train1,y_test1 = train_test_split(x,y, test_size = .30, random_state = 0) #train_size = .70 

In [51]:
x_train1.head()

Height      Weight
3197  69.689848  186.377448
4394  66.299441  159.235988
7711  63.261527  126.426793
7019  62.035319  119.418135
898   67.272171  187.363366

#   KNN   Classifier  weights='uniform' 

In [52]:
k_nei_cls = KNeighborsClassifier(weights= 'uniform',n_neighbors=99)

In [53]:
k_nei_cls.fit(x_train1, y_train1)

KNeighborsClassifier(n_neighbors=99)

In [54]:
kc_uni_score = k_nei_cls.score(x_test1,y_test1)
kc_uni_score

0.9115699259836385

In [55]:
predcition4 = k_nei_cls.predict(x_test1)

In [56]:
predcition4

array([1, 1, 0, ..., 1, 1, 0])

In [57]:
x_test1.iloc[-1, :]

Height     63.939973
Weight    139.495957
Name: 5034, dtype: float64

In [58]:
y_test1.iloc[-1]

Gender    0
Name: 5034, dtype: int32

In [59]:
k_nei_cls.predict([x_test1.iloc[-1, :]])

array([0])

In [60]:
mean_absolute_error(y_test1,predcition4)

0.0884300740163615

In [61]:
mean_squared_error(y_test1,predcition4)

0.0884300740163615

# KNN   Classifier  weights='distance' 

In [62]:
k_nei_cls_dis = KNeighborsClassifier(weights= 'distance',n_neighbors=99)

In [63]:
k_nei_cls_dis.fit(x_train1, y_train1)

KNeighborsClassifier(n_neighbors=99, weights='distance')

In [64]:
kc_dis_score = k_nei_cls_dis.score(x_test1,y_test1)
kc_dis_score

0.9131281651733542

In [65]:
predcition5 = k_nei_cls.predict(x_test1)

In [66]:
predcition5

array([1, 1, 0, ..., 1, 1, 0])

In [67]:
k_nei_cls_dis.predict([x_test1.iloc[-1, :]])

array([0])

In [68]:
mean_absolute_error(y_test1,predcition4)

0.0884300740163615

#  Compare Algorithm

In [69]:
print("Linear Regression:", lr_score)
print("KNN Regressor weights= uniform", kr_uni_score)
print("KNN Regressor weights=distance:", kr_dis_score)
print("KNN Classifier:", kc_uni_score)
print("KNN Classifier:", kc_dis_score)

Linear Regression: 0.905995960709116
KNN Regressor weights= uniform 0.9019067489887957
KNN Regressor weights=distance: 0.8869868902498507
KNN Classifier: 0.9115699259836385
KNN Classifier: 0.9131281651733542
